name: Continous Deployment
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.19.0
      - name: NPM Install
        run: npm i
      - name: Deploy
        run: npx cross-env MINI_APPS_ACCESS_TOKEN=${{ secrets.VK_DEPLOY_TOKEN }} npm run deploy

        